require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude
    
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**'

Layout/CaseIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*.rb'
  
Metrics/AbcSize:
  Max: 24

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8
  
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 12

RSpec/ExampleLength:
  Max: 32

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
