dist: trusty
language: ruby
rvm:
  - 2.6.0
services:
  - postgresql
addons:
  postgresql: "9.6"
script:
  - bundle exec rake db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop
after_success:
  - bash <(curl -s https://codecov.io/bash)